### ISSUE TITLE
 After I click rules and options buttons nothing happens

### ISSUE THREAD

**Issue by miswarowski** [sungry/CS177#108]
Sometimes after I click rules and options buttons nothing happens. Expected game to show appropriate screen. Additionally this always happens after I go to the menu screen from the options screen.

**Comment by kokixi** [comment]
what version do you have? we don't have rules buttons anymore. I've just tested them and everything is working on my machine. did you get the latest changes?

**Comment by miswarowski** [comment]
version#6. i have windows 8, and i tried both explorer and firefox.

**Comment by kokixi** [comment]
This doesn't happen anymore in version 7. It was fixed by @EricSFChu
