### ISSUE TITLE
Need final design decisions on core gameplay

### ISSUE THREAD

**Issue by designerzim** [sungry/CS177#11]
Enemies (types) - details such as stationary or moving? 
All enemies cause fail on collision(?)
("Enemies" include hazards and obstacle collisions)

Power-ups (types and variety) - increasing score and/or slowing speed (going slower is easier)

Definitions need to firm enough to make art for them. Specific values and functionality can be tweaked in code as we test.

**Comment by frostelicus** [comment]
Obstacles/Hazards - Stationary - collision with these will end the run(fail) forcing the player to jump over them These will take the form of students and faculty aka enemies

We currently have two power-ups - those that add to your score and those that subtract from your score.  We should drop the ones that subtract from your score, they are too punishing.  The player has enough trouble as of right now staying alive.  With the addition of obstacles the punishment on the player will be too severe.  

Adding in a rare power up that causes slowdown would be good, making avoiding obstacles easier.  Unsure as of right now what these power-ups should be represented as in game.  

Also when increasing difficulty we can have the character start out running at “normal speed” increasing speed until it reaches “max speed”.   A little faster than what we have now would make for a good “max speed” while a little slower would be a good place to start for “normal speed”.  This will come into play for how our level is planned out.  The first 5 seconds or so will be a runway giving the player chance to test the jump mechanic.  After that I propose we layout and design enough of level to last for about 60 seconds of running before it repeats.  This will allow us to have an easier section(the first 20 or so seconds) for the player as the speed is increasing and obstacles are introduced, then a harder section(this is the part that will repeat endlessly - enough level design for 30 or so seconds on its own).   

When I say design a level I mostly am referring to platform and obstacle placement and not referring to the background being extended.
