### ISSUE TITLE
Put "press space to jump" in the direction of the movement. 

### ISSUE THREAD

**Issue by angelsonly** [sungry/CS177#110]
Liz feedback was:
1. She was looking in the direction of the character movement and therefore did not notice the instruction Press space to jump. She was pressing the arrow up to jump. It took her several times to figure it out. It is blurred and faded and mixed with background. She advised put the instructions in the direction of the character movement.

**Comment by frostelicus** [comment]
This is a great idea!  As of right now it overlaps on our player character.  We should move it to the right slightly above him which might help suggest where he will be jumping.

**Comment by ghost** [comment]
#118 fixes this issue
