### ISSUE TITLE
Music is too innoying

### ISSUE THREAD

**Issue by angelsonly** [sungry/CS177#111]
Confirmed by 3 users.

**Comment by frostelicus** [comment]
While I am composing something for the game over screen, the in-game music will not be changed.  #wontfix

**Comment by sungry** [comment]
@angelsonly 
Thank you for your feedback. I would advise that you be more specific as in how it is 'annoying' or how to approach the issue. The word 'annoying' is very vague - doesn't leave people much to work on.
Also, please use kinder words to the composer who took time to write the music over the holidays. :)

**Comment by frostelicus** [comment]
I agree it is annoying its current state due to having to listen to it at three different tempos, but I have a feeling it will be less so when I finish our game over track.
