### ISSUE TITLE
Put an indication of the new level for a user "Congrats, you are on level 2"

### ISSUE THREAD

**Issue by angelsonly** [sungry/CS177#112]

**Comment by frostelicus** [comment]
We don't have a second level.  I think the basics of the game need to be explained further through our tutorial or a rules page.

**Comment by designerzim** [comment]
What did they think level 2 was?

**Comment by kokixi** [comment]
I think what they called level 2 is when the character speed is increased

**Comment by EricSFChu** [comment]
Added sound to signify difficulty increase
