### ISSUE TITLE
get instructor to test the version 7

### ISSUE THREAD

**Issue by ghost** [sungry/CS177#127]
please get the instructor to test version 7

**Comment by miswarowski** [comment]
some comments that the instructor said (which could also be that he is joking too!):
- coffee? there are no cookies?
- just one life? there are no extra lives? why is it that only one head that can kill me? (he wants to have more lives for the game)
- nice background, nice sounds (but he did not play it that long, only four or five attempts)
- what is the name of our game? is it Bad Dream?
- can i jump higher? i want to get the coffee in the higher position
- is it possible to have some leeway to move forward of backwards in the game, even though the character will be constantly move forward in this game?

some stuff i noticed when the instructor was playing the game:
- some heads blend in to the background, so the instructor may not see where the obstacles are coming
- pressed the second jump when the first jump did not reach its maximum height
- when he found out the option button did not quite work as intended, he randomly spam and click the option button and found out it somewhat works
- did not find out about the easter egg dash button
- his right hand (index, middle, ring) was instinctively placed in the up down left right button
- his left hand instinctive placed around the spacebar area

**Comment by miswarowski** [comment]
- instructor also died when the game went out of focus on the laptop
