### ISSUE TITLE
Game Start: "Jump" tutorial instruction

### ISSUE THREAD

**Issue by designerzim** [sungry/CS177#20]
The first 5 seconds of the game will be a clear path.

~1 second into the game, text on the upper half of the screen will appear saying: "Press Space to Jump"

This will go away upon jumping or game over condition (and for debug purposes, possibly time).

**Comment by EricSFChu** [comment]
okay this can be done by setting a system time variable at the beginning of the of the game.
at game time > system time + 5 seconds we can start spawning things. - needs to be a public variable
The good things is we only have to add this to the spawn script once.

**Comment by designerzim** [comment]
There is now a jump tutorial.
