### ISSUE TITLE
placeholder enemy art

### ISSUE THREAD

**Issue by ghost** [sungry/CS177#29]
make a placeholder for an enemy student head

**Comment by romanborsov** [comment]
![enemy1](https://cloud.githubusercontent.com/assets/4162912/11430413/33d8f2a4-943b-11e5-80e8-f846e96ba362.png)
![enemy2](https://cloud.githubusercontent.com/assets/4162912/11430414/33daf004-943b-11e5-84d0-2314a8d0c50e.jpg)

**Comment by frostelicus** [comment]
Love the head but lets erase the body.  Floating heads make for terrifying enemies.

**Comment by romanborsov** [comment]
![head02](https://cloud.githubusercontent.com/assets/4162912/11450006/f08d9e76-9540-11e5-953e-b58c9d761e06.png)
![head01](https://cloud.githubusercontent.com/assets/4162912/11450007/f091823e-9540-11e5-8f0b-093d590d9073.png)

**Comment by romanborsov** [comment]
![1](https://cloud.githubusercontent.com/assets/4162912/11615631/07ea312a-9c1b-11e5-9816-acff2238b070.png)
![1_colored](https://cloud.githubusercontent.com/assets/4162912/11615630/07e8891a-9c1b-11e5-9a07-2c69ccd13c51.png)
![1_filtered](https://cloud.githubusercontent.com/assets/4162912/11615628/07e1f0a0-9c1b-11e5-9d93-92f92f830daa.png)
![2](https://cloud.githubusercontent.com/assets/4162912/11615632/07eaef0c-9c1b-11e5-8f3b-77afa972c5aa.png)
![2_colored](https://cloud.githubusercontent.com/assets/4162912/11615629/07e2944c-9c1b-11e5-9e72-61c2e06290ab.png)
![2_filtered](https://cloud.githubusercontent.com/assets/4162912/11615633/07f962d0-9c1b-11e5-912a-c39527b3462c.png)
![3](https://cloud.githubusercontent.com/assets/4162912/11615634/07fc67b4-9c1b-11e5-90ba-232e21e2c077.png)
![3_colored](https://cloud.githubusercontent.com/assets/4162912/11615635/07fd8b6c-9c1b-11e5-8d3b-88073a0a1845.png)
![3_filtered](https://cloud.githubusercontent.com/assets/4162912/11615636/08039b7e-9c1b-11e5-815e-1a2433b0a782.png)
![4](https://cloud.githubusercontent.com/assets/4162912/11615638/0805cdcc-9c1b-11e5-9a9d-1cdfe80e1eee.png)
![4_colored](https://cloud.githubusercontent.com/assets/4162912/11615637/0804ff3c-9c1b-11e5-8085-1019e5b1c8f8.png)
![4_filtered](https://cloud.githubusercontent.com/assets/4162912/11615639/08129084-9c1b-11e5-9095-7911791f4f5f.png)
![5](https://cloud.githubusercontent.com/assets/4162912/11615640/0814b85a-9c1b-11e5-83b7-bbc73a6e8c2e.png)
![5_colored](https://cloud.githubusercontent.com/assets/4162912/11615641/081807c6-9c1b-11e5-9446-50b76665638c.png)
![5_filtered](https://cloud.githubusercontent.com/assets/4162912/11615642/081f73c6-9c1b-11e5-9a51-f0e92e3ddd67.png)
![6](https://cloud.githubusercontent.com/assets/4162912/11615643/08237d2c-9c1b-11e5-9ef8-621b9ecbd467.png)
![6_colored](https://cloud.githubusercontent.com/assets/4162912/11615644/0827c6c0-9c1b-11e5-971e-34633fae048f.png)
![6_filtered](https://cloud.githubusercontent.com/assets/4162912/11615645/082a1a2e-9c1b-11e5-8600-fe3f9d4516f8.png)

**Comment by romanborsov** [comment]
![7_colored](https://cloud.githubusercontent.com/assets/4162912/11616122/3f0be5a6-9c28-11e5-9b5b-6b5de90fea63.png)

**Comment by romanborsov** [comment]
Let's use "colored" ones.

**Comment by designerzim** [comment]
Created another issue for the creation of the content. This was for creating the first head in the game.

**Comment by designerzim** [comment]
Which was done last week.

**Comment by designerzim** [comment]
See also #103 and #104
