### ISSUE TITLE
 Cannot start the game in Chrome web browser

### ISSUE THREAD

**Issue by miswarowski** [sungry/CS177#3]
Chrome console output:
 "You are using a version of Chrome that does not currently support the Unity Web Player plugin needed to run this app."

**Comment by designerzim** [comment]
Will Not Fix/Can't Fix

Google has intentionally made Chrome incompatible with the Unity plug-in.

**Comment by designerzim** [comment]
...but there is a webGL version that we can experiment with later that is based in html5.

No promises.
