### ISSUE TITLE
Background for MenuScreen

### ISSUE THREAD

**Issue by kokixi** [sungry/CS177#30]
Background for menuScreen without buttons

**Comment by romanborsov** [comment]
![screen1](https://cloud.githubusercontent.com/assets/4162912/11430404/00d28f14-943b-11e5-9dba-633e105b83d9.png)

**Comment by romanborsov** [comment]
![screen2](https://cloud.githubusercontent.com/assets/4162912/11430596/0c7aabbe-943e-11e5-80a1-f28fe499f4f8.png)

**Comment by romanborsov** [comment]
![screen22](https://cloud.githubusercontent.com/assets/4162912/11430913/a4e6ab38-9442-11e5-8220-6ed939d93b95.png)

less colors

**Comment by ghost** [comment]
is it possible to edit the following image:

https://cloud.githubusercontent.com/assets/4162912/11430404/00d28f14-943b-11e5-9dba-633e105b83d9.png

such that the RULES button is removed, whereas the START and OPTION buttons (including those 2 words) are still kept?

**Comment by romanborsov** [comment]
will be changed later this evening

**Comment by romanborsov** [comment]
![menuscreen](https://cloud.githubusercontent.com/assets/4162912/11492830/061b6b16-97a7-11e5-9660-10d594f204d5.png)
