### ISSUE TITLE
version 4 background problems. 

### ISSUE THREAD

**Issue by miswarowski** [sungry/CS177#33]
Background is not smoothly moving, it is shaking as earthquake constantly. "Lunch Box" sign is doubled and fuzzy during background moving. It hurts eyes during play.

**Comment by designerzim** [comment]
Thanks for catching this! I noticed the trees shaking last night. Does earthquake refer to the trees or just the lunch box? You can write up each background element as a separate issue, as they probably aren't a single fix.

**Comment by miswarowski** [comment]
Yes, trees also disappear and appear.

**Comment by frostelicus** [comment]
Encountered this issue myself.  Glitches in the background as well as in the score display.  I am assuming the background is due to multiple layers being stacked on one another as opposed to a single clean image.

**Comment by frostelicus** [comment]
Background glitches still exists in version 6.  We discussed in class that the trees were spawning in early or late not 100% sure.

**Comment by kokixi** [comment]
fixed on #94. Now the trees are showing smoothly
