### ISSUE TITLE
Obstacles function.

### ISSUE THREAD

**Issue by miswarowski** [sungry/CS177#34]
First obstacle - "student head" doesn't function: Runner runs through it without being stopped.

**Comment by frostelicus** [comment]
Also have encountered this error

**Comment by ghost** [comment]
i think this is the same problem as issue #47

**Comment by frostelicus** [comment]
Looks like you guys fixed this in version 6!  Please close if so.

**Comment by EricSFChu** [comment]
Fixed by Ana Maria
