### ISSUE TITLE
Settings screen background

### ISSUE THREAD

**Issue by kokixi** [sungry/CS177#36]
Background for the settings screen. Maybe some of the buildings in a light color?

**Comment by romanborsov** [comment]
![sciencehall backgr](https://cloud.githubusercontent.com/assets/4162912/11430305/52df53f2-9439-11e5-9f10-8975f053bf4c.png)

will this work?

**Comment by ghost** [comment]
it is possible to add more tint (or white) to this image? the contrast between the buttons for this settings/option scene/screen is very bad since both this image and the buttons are of bright colours

**Comment by romanborsov** [comment]
![52df53f2-9439-11e5-9f10-8975f053bf4c](https://cloud.githubusercontent.com/assets/4162912/11475037/1c2f30da-9730-11e5-8d12-330cfdd06038.png)

**Comment by romanborsov** [comment]
![52df53f2-9439-11e5-9f10-8975f053bf41](https://cloud.githubusercontent.com/assets/4162912/11475120/861c9e88-9730-11e5-947c-b71590a60b3f.png)

**Comment by romanborsov** [comment]
![52df53f2-9439-11e5-9f10-8975f053bf43](https://cloud.githubusercontent.com/assets/4162912/11475272/5327f10c-9731-11e5-957f-d3f8b610e89f.png)

**Comment by romanborsov** [comment]
![options](https://cloud.githubusercontent.com/assets/4162912/11616114/1a608a22-9c28-11e5-9d52-b956b81206c6.png)
