### ISSUE TITLE
Too long start 

### ISSUE THREAD

**Issue by miswarowski** [sungry/CS177#4]
The game starts  6 seconds after you click the start button. (Firefox and I-explorer). Can time be reduced on half?

**Comment by frostelicus** [comment]
Unable to recreate this issue myself.  Can anyone else confirm?

**Comment by ghost** [comment]
I cannot recreate this issue either, but maybe because this issue is referring to the first web version, but now we are in the fourth web version. If this problem resurfaces in the newer versions, just reopen this issue.
