### ISSUE TITLE
(Unity-Editor-Build) Start and Option buttons don't work upon click

### ISSUE THREAD

**Issue by designerzim** [sungry/CS177#42]
I'm referring to running the game in the unity editor as a Unity-Editor-Build.

Roll-over color change currently works. Clicking on one of the selections does not load.

There is a warning flag at the bottom of the editor after running the MainMenu scene.
![screen shot 2015-11-27 at 8 11 27 pm](https://cloud.githubusercontent.com/assets/126969/11450053/1f00b16a-9543-11e5-8fe4-2fc14092a3dc.png)

A double click on the error will highlight the MainMenu object.

It looks like the mainMenu.cs file is attached, and it is not missing from my local machine. 

The Main Menu (Script) section, however, has a complaint about compile errors. There's no details on what the problem might be, nor does MonoDevelop report any problems.

**Comment by kokixi** [comment]
This isn't a problem anymore. It was fixed on #54
