### ISSUE TITLE
Player slow down when hits power ups

### ISSUE THREAD

**Issue by kokixi** [sungry/CS177#61]
When the player hits a power ups or an enemy, he slow down

**Comment by EricSFChu** [comment]
will fix. Change physics so that the transfer of energy isn't so great that the player stops.

**Comment by frostelicus** [comment]
I would recommend removing the physics here and just having a sound effects to signifify collision.

**Comment by EricSFChu** [comment]
Physics have been removed and power ups have reverted to prototype functionality.
