### ISSUE TITLE
Get Jenkins working with the unityTree sub-directory

### ISSUE THREAD

**Issue by designerzim** [sungry/CS177#73]
Close this when Jenkins is working with our build.

**Comment by designerzim** [comment]
We may need to use this: https://wiki.jenkins-ci.org/display/JENKINS/Unity3dBuilder+Plugin

**Comment by miswarowski** [comment]
Got succesfull build. Here is Console Output:

Started by user anonymous
Building in workspace /var/spool/jenkins/jobs/TimeWaster/workspace

> git rev-parse --is-inside-work-tree # timeout=10
> Fetching changes from the remote Git repository
> git config remote.origin.url https://github.com/miswarowski/CS177.git # timeout=10
> Fetching upstream changes from https://github.com/miswarowski/CS177.git
> git --version # timeout=10
> git -c core.askpass=true fetch --tags --progress https://github.com/miswarowski/CS177.git +refs/heads/_:refs/remotes/origin/_
> git rev-parse refs/remotes/origin/master^{commit} # timeout=10
> git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
> Checking out Revision bf845a37a286ffb9052b0dfd6dfe38d344e2ee92 (refs/remotes/origin/master)
> git config core.sparsecheckout # timeout=10
> git checkout -f bf845a37a286ffb9052b0dfd6dfe38d344e2ee92
> First time build. Skipping changelog.
> Path To MSBuild.exe: /usr/lib/mono/4.0/xbuild.exe
> Executing the command /usr/lib/mono/4.0/xbuild.exe EndlessRun.sln from /var/spool/jenkins/jobs/TimeWaster/workspace
> [workspace] $ /usr/lib/mono/4.0/xbuild.exe EndlessRun.sln
> XBuild Engine Version 2.10.8.1
> Mono, Version 2.10.8.1
> Copyright (C) Marek Sieradzki 2005-2008, Novell 2008-2011.

Build started 12/10/2015 8:28:27 PM.

---

/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/SyntaxTree/UnityVS/2015/UnityVS.CSharp.targets, to import. Ignoring.
/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.Editor.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/SyntaxTree/UnityVS/2015/UnityVS.CSharp.targets, to import. Ignoring.
Project "/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.sln" (default target(s)):
    Target ValidateSolutionConfiguration:
        Building solution configuration "Debug|Any CPU".
    Target Build:
        Project "/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.csproj" (default target(s)):
/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/SyntaxTree/UnityVS/2015/UnityVS.CSharp.targets, to import. Ignoring.
        Done building project "/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.csproj".
        Project "/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.Editor.csproj" (default target(s)):
/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.Editor.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/SyntaxTree/UnityVS/2015/UnityVS.CSharp.targets, to import. Ignoring.
        Done building project "/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.Editor.csproj".
Done building project "/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.sln".

Build succeeded.

Warnings:

/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/SyntaxTree/UnityVS/2015/UnityVS.CSharp.targets, to import. Ignoring.
/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.Editor.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/SyntaxTree/UnityVS/2015/UnityVS.CSharp.targets, to import. Ignoring.

/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.sln (default targets) ->
(Build target) ->
/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.csproj (default targets) ->

```
/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/SyntaxTree/UnityVS/2015/UnityVS.CSharp.targets, to import. Ignoring.
```

/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.sln (default targets) ->
(Build target) ->
/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.Editor.csproj (default targets) ->

```
/var/spool/jenkins/jobs/TimeWaster/workspace/EndlessRun.CSharp.Editor.csproj:  warning : Could not find project file /usr/lib/mono/xbuild/SyntaxTree/UnityVS/2015/UnityVS.CSharp.targets, to import. Ignoring.
```

Finished: SUCCESS
