### ISSUE TITLE
Decouple spawners from a fixed time

### ISSUE THREAD

**Issue by designerzim** [sungry/CS177#81]
The faster the player goes, the farther apart power-ups and enemies spawn.

Either the spawners should use distance as the delta, so that a faster player encounters the same amount of spawns, or perhaps applying the percentage change of to the spawner frequency.

**Comment by frostelicus** [comment]
Because the player is moving faster, they are also jumping further.  I think leaving the spawns spread out in this case is fine.  The game still remains difficult because the player is committing to these longer jumps.

**Comment by EricSFChu** [comment]
This feature is already implemented in version 6. There is a delta time algorithm that decreases spawn time over time that correlates with increased player speed.
