### ISSUE TITLE
Check the functional spec for accuracy

### ISSUE THREAD

**Issue by designerzim** [sungry/CS177#82]
Check the functional spec for accuracy: https://docs.google.com/document/d/1Bo-EpJk44Mouh8B656O5ui7HwNDy4gI0aFS2-5W8Un4/edit?pli=1

Submit issue reports for any differences in the spec from the current project (test on development preferred, but use the latest web build if you can't get that to work)

**Comment by ghost** [comment]
the functional spec needs some updating, so i will need to look at it

**Comment by ghost** [comment]
also, i will need to double check the requirements too, which is #98

**Comment by angelsonly** [comment]
I was checking the Fun Specs for accuracy and assigned the issue so you need to give it back to me. And I will close it.
