### ISSUE TITLE
Background needed for Game Over Screen

### ISSUE THREAD

**Issue by kokixi** [sungry/CS177#90]
maybe some background with the enemies faces around the Game over text?

**Comment by romanborsov** [comment]
![gameover](https://cloud.githubusercontent.com/assets/4162912/11615751/180e9c28-9c1e-11e5-8b49-e569ce706d2c.png)

**Comment by romanborsov** [comment]
![gameover](https://cloud.githubusercontent.com/assets/4162912/11643161/ddcc6296-9cf6-11e5-993a-bf61f33b1250.jpg)
