### ISSUE TITLE
create PDF document file

### ISSUE THREAD

**Issue by ghost** [sungry/CS177#96]
We need to create a google document file to do the following:

Produce a PDF report describing the project. It must include team member roles, requirements, functional specification, technical specification, the results of multiple rounds of user testing, and user documentation. Each member of the team must turn in a copy.

**Comment by designerzim** [comment]
We already have google docs for:
requirements;
functional spec;

The others need to be created, and the PDF can be compiled from that.

The creation of the technical spec is covered by #84, and user documentation will (hopefully) be covered by our tutorial.

We need team roles and user testing results.

**Comment by designerzim** [comment]
Renaming this to create PDF since we don't necessarily need to create a single google doc that has all these.

**Comment by designerzim** [comment]
This https://chrome.google.com/webstore/detail/pdf-mergy/hgecghmkcdefnknohcimkoemhaofpoha?hl=en
or
this https://chrome.google.com/webstore/detail/pdf-merge-pdf-files-merge/ndolbcaghkmhjhgggldkgjibdilpbdbm?hl=en-US

Should help for merging the multiple docs

**Comment by sungry** [comment]
closing!
